services:
  app:
    build: 
      context: .
      dockerfile: ./config/docker/app/Dockerfile
    container_name: planit-api
    volumes: 
      - ./:/var/www/
      - ./config/docker/app/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    ports:
      - "${SERVER_PORT}:8080"
    entrypoint: /usr/local/bin/entrypoint.sh
    networks:
      - planit-network
  nginx:
    image: nginx:alpine
    container_name: planit-api-webserver
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - "80:80"
    volumes: 
      - ./config/docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./config/docker/nginx/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    depends_on:
      - app
    entrypoint: /usr/local/bin/entrypoint.sh
    networks:
      - planit-network

networks:
  planit-network:
    driver: bridge