version: '3'

services:
  app:
    build: 
      context: ./docker/go
    container_name: planit-api
    volumes: 
      - .:/var/www
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - planit-network

  db:
    image: mysql:latest
    container_name: planit-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_db_name
    networks:
      - planit-network

  nginx:
    image: nginx:alpine
    container_name: planit-api-webserver
    ports:
      - "80:80"
    volumes: 
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - planit-network

networks:
  planit-network:
    driver: bridge