name: Create Branch on Comment

on:
  issue_comment:
    types: [created]

jobs:
  create-branch:
    if: startsWith(github.event.comment.body, '/create-branch')
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACTION_TOKEN }}

    - name: Get issue details
      id: issue
      run: |
        echo "title=${{ github.event.issue.title }}" >> $GITHUB_ENV
        echo "number=${{ github.event.issue.number }}" >> $GITHUB_ENV

    - name: Create a New Branch and Comment It on Issue
      env:
        GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
      run: |
        git fetch --all
        BASE_BRANCH_NAME="API-${{ env.number }}-$(echo "${{ env.title }}" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]- ' | tr ' ' '-')"
        EXISTING_BRANCHES=$(git branch -r | grep "origin/$BASE_BRANCH_NAME" | sed 's/.*\///')
        if [[ -z "$EXISTING_BRANCHES" ]]; then
          NEW_BRANCH_NAME="$BASE_BRANCH_NAME"
        else
          MAX=0
          for BRANCH in $EXISTING_BRANCHES; do
            if [[ "$BRANCH" =~ $BASE_BRANCH_NAME-([0-9]+)$ ]]; then
              NUM=${BASH_REMATCH[1]}
              if [[ $NUM -gt $MAX ]]; then
                MAX=$NUM
              fi
            fi
          done
          NEW_BRANCH_NAME="$BASE_BRANCH_NAME-$((MAX + 1))"
        fi
        echo "New branch name: $NEW_BRANCH_NAME"
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b $NEW_BRANCH_NAME
        git push origin $NEW_BRANCH_NAME
        echo "commenting on issue..."
        COMMENT_BODY="A new branch named \`$NEW_BRANCH_NAME\` has been created for this issue."
        curl -s -H "Authorization: token $GITHUB_TOKEN" \
           -H "Content-Type: application/json" \
           -d "{\"body\": \"$COMMENT_BODY\"}" \
           "https://api.github.com/repos/${{ github.repository }}/issues/${{env.number}}/comments"